import express from 'express';
import supplierController from '../controllers/supplier.controller';
import validateSupplier from '../middleware/validators/suppliersValidator';
const router = express.Router();
router.get('/all', supplierController.getAll);
router.get('/id/:id', supplierController.getById);
router.post('/create/', validateSupplier, supplierController.create);
router.patch('/update/:id', validateSupplier,supplierController.update);
router.delete('/remove/:id', supplierController.softDelete);
router.get('/deleted/', supplierController.getDeleted);
router.post('/restore/:id', supplierController.restore);
router.delete('/delete/:id', supplierController.hardDelete);
router.get('/check/uniqueName', supplierController.checkNameUnique);
router.get('/check/uniqueEmail', supplierController.checkEmailUnique);
router.get('/check/uniquePhone', supplierController.checkPhoneNumberUnique);
export default router;
